refactor(hw02): clean tests
OtusGolang/home_work pull request #21
Opened 2020-12-12 10:10 UTC by kulti

Сделал тетсы компактнее и чище.

Я почти всегда отделяю ошибочные кейзы от нормальных. Так тесты получаются короче и лаконичнее. На занятиях тоже рекомендую студентам так делать. Некоторые студенты переписывают тесты на такой вид.

@Antonboom, если у тебя нет возражений, то я могу постепенно подчистить тесты. Пока делаю разборы ДЗ все равно их правлю.

2020-12-12 18:55 UTC, Antonboom commented on hw02_unpack_string/unpack_test.go
> +		tc := tc
без использования t.Parallel излишне.

или ты так - на всякий?

2020-12-12 18:59 UTC, Antonboom requested changes
Отписал

2020-12-12 18:59 UTC, Antonboom commented on hw02_unpack_string/unpack_test.go
> +		tc := tc
без использования t.Parallel излишне.

или ты так - на всякий?

2020-12-12 18:59 UTC, Antonboom commented on hw02_unpack_string/unpack_test.go
> +			require.Error(t, err, ErrInvalidString)
`require.Error` проверяет, что ошибка not nil, а `ErrInvalidString` у тебя попал в msg - это работает вообще?

ты, наверное, хотел [ErrorIs](https://github.com/stretchr/testify/blob/master/require/require.go#L285), но он ещё не в релизе :(

можно заменить на `require.True(t, errors.Is(...))`

2020-12-12 19:23 UTC, kulti commented on hw02_unpack_string/unpack_test.go
> +		tc := tc
Ага, на всякий случай — все-таки замыкание внутри цикла. Привычка уже.

2020-12-12 19:23 UTC, kulti commented on hw02_unpack_string/unpack_test.go
> +			require.Error(t, err, ErrInvalidString)
Блин, накосячил я. Поправил.

2020-12-13 18:47 UTC, Antonboom approved these changes

2020-12-13 18:47 UTC, merged