hw05: fix for linter "gocritc"
OtusGolang/home_work pull request #25
Opened 2021-01-24 13:55 UTC by technobulka

https://go-critic.github.io/overview.html#captLocal-ref

2021-01-24 14:02 UTC, Antonboom requested changes

2021-01-24 14:02 UTC, Antonboom commented on hw05_parallel_execution/run.go
> +func Run(tasks []Task, n, m int) error {
тогда и комментарий выше следует поменять + там ещё точки не хватает в конце

2021-01-25 06:34 UTC, kulti commented on hw05_parallel_execution/run.go
> +func Run(tasks []Task, n, m int) error {
Думаю, еще в README нужно поправить для консистентности.

2021-01-27 10:07 UTC, technobulka commented on hw05_parallel_execution/run.go
> +func Run(tasks []Task, n, m int) error {
точка в конце комментария? вроде, в других шаблонах точек в комментариях не было

2021-01-27 10:19 UTC, Antonboom commented on hw05_parallel_execution/run.go
> +func Run(tasks []Task, n, m int) error {
странно, что godot не ругается

видимо, выключен

2021-01-27 11:01 UTC, technobulka commented on hw05_parallel_execution/run.go
> +func Run(tasks []Task, n, m int) error {
https://github.com/OtusGolang/home_work/blob/master/.golangci.yml
вижу, что он есть в списке, но тревис не ругался

2021-01-27 12:07 UTC, Antonboom approved these changes

2021-01-27 12:07 UTC, merged