add sync script
OtusGolang/home_work pull request #37
Opened 2021-05-04 17:56 UTC by kulti

2021-05-05 06:20 UTC, Antonboom requested changes

2021-05-05 06:20 UTC, Antonboom commented on .scripts/sync.sh
> +for f in *; do
а что с чем этот скрипт поможет синкать?

простите, я не понял :(

2021-05-06 04:18 UTC, kulti commented on .scripts/sync.sh
> +for f in *; do
Да, не успел вчера дескрипшен написать. Думал чуть позже напишу, но слишком много дел навалилось. 

Текущий подход к обновлению репы из шаблона какой-то запарный, как по мне. Я подумал это немного автоматизировать.

В каждой папочке лежит .sync-файл. Студент, который сделал ДЗ удаляет этот .sync-файл из папки со сделанными ДЗ. В какой-то момент мы обновляем шаблон. Студент клонирует себе репозиторий с шаблоном и, чтобы в ручную не переносить нужные файлы может использовать этот скрипт.

Допустим, ДЗ и шаблон лежат в этих папках:
```
├── otus_hw
└── otus_hw_tmpl
```

Скрипт пока работает только из папки с шаблоном (otus_hw_tmpl) — `./.scripts/sync.sh ../otus_hw`. Скопируются только те папк, где у студента остался .sync-файл.

2021-05-06 04:35 UTC, Antonboom commented on .scripts/sync.sh
> +#!/bin/bash
а что делать виндузятникам? :)

или хрен с ними, и так `test.sh` в дзшках

2021-05-06 04:36 UTC, Antonboom commented on .scripts/sync.sh
> +for f in *; do
Надо тогда переписать/дописать в секцию "Как обновить свой репозиторий базовым (шаблонным)?"

https://github.com/OtusGolang/home_work/wiki/%5B%D0%A1%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0%D0%BC%5D-%D0%9F%D1%80%D0%BE%D1%86%D0%B5%D1%81%D1%81-%D1%81%D0%B4%D0%B0%D1%87%D0%B8-%D0%94%D0%97#%D0%9A%D0%B0%D0%BA-%D0%BE%D0%B1%D0%BD%D0%BE%D0%B2%D0%B8%D1%82%D1%8C-%D1%81%D0%B2%D0%BE%D0%B9-%D1%80%D0%B5%D0%BF%D0%BE%D0%B7%D0%B8%D1%82%D0%BE%D1%80%D0%B8%D0%B9-%D0%B1%D0%B0%D0%B7%D0%BE%D0%B2%D1%8B%D0%BC-%D1%88%D0%B0%D0%B1%D0%BB%D0%BE%D0%BD%D0%BD%D1%8B%D0%BC

2021-05-09 15:09 UTC, kulti commented on .scripts/sync.sh
> +#!/bin/bash
Думаю, их не очень много. Можно будет потом переписать скрипт на go. Мне на bash'e это проще и быстрее было :)

2021-05-09 15:09 UTC, merged